// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Kentico.Kontent.Statiq.Memoirs.Models
{
    public partial class Author
    {
        public const string Codename = "author";
        public const string AvatarImageCodename = "avatar_image";
        public const string BioCodename = "bio";
        public const string ContactsCodename = "contacts";
        public const string EmailCodename = "email";
        public const string NameCodename = "name";

        public IEnumerable<IAsset> AvatarImage { get; set; }
        public string Bio { get; set; }
        public IEnumerable<object> Contacts { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}