// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Kentico.Kontent.Statiq.Memoirs.Models
{
    public partial class Contact
    {
        public const string Codename = "contact";
        public const string IconCodename = "icon";
        public const string NameCodename = "name";
        public const string UrlCodename = "url";

        public string Icon { get; set; }
        public string Name { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Url { get; set; }
    }
}