// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Kentico.Kontent.Statiq.Memoirs.Models
{
    public partial class Quote
    {
        public const string Codename = "quote";
        public const string AttributionCodename = "attribution";
        public const string ContentCodename = "content";

        public string Attribution { get; set; }
        public string Content { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}